FROM bitnami/spark:3.5

USER root

RUN pip install --no-cache-dir \
    pyspark==3.5.0 \
    pymongo==4.6.1 \
    boto3==1.34.11 \
    psycopg2-binary==2.9.9

COPY spark_jobs/ /opt/spark-jobs/

USER 1001
